name: Test on RISC-V

on: [workflow_dispatch, pull_request]

jobs:
  test:
    runs-on: self-hosted
    env:
      PATH: /home/ubuntu/dotnet:$PATH
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          dotnet build -c Release

      - name: Generate output
        run: ./bin/Release/WaveFunctionCollapse
